services:
  - type: web
    name: casa-de-apostas-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://seu_usuario:sua_senha@cluster0.mongodb.net/casa-de-apostas
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 24h 